### PR TITLE
hal: v0.12.1

### PR DESCRIPTION
**Pull request by jordens**

### CODE REVIEW

**Comment by jordens** [comment]
bors try

**Comment by jordens** [comment]
@nkrackow FYI

**Comment by jordens** [comment]
bors try

**Comment by jordens** [comment]
bors try

**Review by ryan-summers — APPROVED** [review]
Wow those IO changes are super clean. I imagine the compiler can actually figure out which AFx you need to convert into based on the accepted type signatures of the driver they the pins are being handed to (and only needs specification in certain cases).

That's super handy and eliminates the mental need to lookup which alternate function is needed. Nice change!

**Comment by jordens** [comment]
I think for things like the AFEs we may actually want to use the type erased pins. Then both AFEs have the same type.

**Pull request merged**
