### PR TITLE
cm7 r0p1 basepri

### PR DESCRIPTION
**Pull request by jordens**

### CODE REVIEW

**Comment by dnadlinger** [comment]
When I looked at this, it seemed like all our hardware was comfortably in the new stepping, also datecode-wise. Do you actually have r0p1 on one of your boards?

**Comment by jordens** [comment]
Are you sure? Got a reference? The app notes and the svd all say r0p1.

**Comment by dnadlinger** [comment]
On the two I've looked at, I got CPUID base 0x411FC271, which should be r1p1 according to http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0489d/BABCIIIA.html.

**Comment by dnadlinger** [comment]
The problem was fixed in r0p2 as per erratum 837070 in https://static.docs.arm.com/epm064408/80/Cortex-M7_Software_Developers_Errata_Notice_v8.pdf.

**Comment by jordens** [comment]
The [STM32H743 errata](https://www.st.com/content/ccc/resource/technical/document/errata_sheet/group0/b8/f4/b7/a3/d1/a0/44/a6/DM00368411/files/DM00368411.pdf/jcr:content/translations/en.DM00368411.pdf) says r0p1. That's what I found first.
But the [system architecture](https://www.st.com/content/ccc/resource/technical/document/application_note/group0/0d/b5/e7/b7/47/0c/4a/ae/DM00306681/files/DM00306681.pdf/jcr:content/translations/en.DM00306681.pdf) says r1p1. And yes, even the oldest one I have is r1p1.

**Comment by jordens** [comment]
@dnadlinger Thanks for the cross check!

**Comment by dnadlinger** [comment]
> The STM32H743 errata and the ST SVD both say r0p1. 

Yes, ST cheekily respun the chip with a new core version without updating the part number…

**Comment by jordens** [comment]
From what I can see in the [forums](https://community.st.com/s/question/0D50X0000BcRH33SQG/stm32h743-cortexm7-core-revision) they never sold that with anything other than r1p1.

**Pull request merged**
