### PR TITLE
compile time features for the cases without Driver and without the headboard

### PR DESCRIPTION
**Pull request by nkrackow**
I'm not sure where exactly to put this best. Having the state machine transitions different depending on compile time features is not possible, right?

### CODE REVIEW

**Review by jordens — CHANGES_REQUESTED** [review]
what's breadboard? what's it's real name?
You can also `#[allow(unused something something)]` to suppress the lint. Whatever feels easier.
Negative `no_X` features are clearly a bad idea. Especially if you then negate them all again! Instead make them positive and change `default-features` if you are really worried about having to pass them.
And consider rather having one feature that allows you to work in your current mockup environment, not two.

**Comment by jordens** [comment]
Then why not call it "laser module" as in the design? It's certainly not a breadboard.

Are you sure the use case without the laser module is well defined? (I.e. written down). Then you can judge whether it's worth it carrying it through as a feature, or whether run-time detection is much easier (`Option<Mcp...>`), or whether it's a hack done by editing the code.

**Comment by nkrackow** [comment]
I mean the likelyhood of driving _a_ laser module with driver is fairly high. It might just not be the ai-artiq module with its specific carrier board. I've called it "ai-artiq-laser-module" now.
I would argue that this is best implemented as a feature, will certainly happen at FBH that they test Driver on another laser module.
The case without Driver is a hack for development, so I've reverted back to just commenting out the one line in this case.

**Comment by nkrackow** [comment]
Do you think run-time detection for the laser module is better? I guess it could be that I wanted to connect the headboard but just failed to do so correctly.

**Comment by jordens** [comment]
It's only better if the features stuff becomes annoying.

**Review by jordens — APPROVED** [review]

**Pull request merged**
