### PR TITLE
factor CPU and board-specific initialisation out of main

### PR DESCRIPTION
**Pull request by cjbe**

### CODE REVIEW

**Comment by jordens** [comment]
Just to confirm: Is this a 1:1 move?

**Comment by cjbe** [comment]
Yes - there is no functional change. I will amend the commit message to make this clear

**Comment by jordens** [comment]
It's ok
bors r+

**Comment by jordens** [comment]
This wasn't a 1:1 move. You converted the entire thing to dos line endings and shuffled the log setup.

**Pull request merged**
