### PR TITLE
add sine to signal generator

### PR DESCRIPTION
**Pull request by svrotter**
Added sine function to signal generator to have the full variety of available signals

### CODE REVIEW

**Comment by jordens** [comment]
What does this offer?
Isn't that already possible by adding -0.25 turns phase_offset?

**Comment by svrotter** [comment]
It is.
But sometimes life is easier when you also give things the names that are easier.
If I'd demodulate in I&Q for example and need to setup LUTs, it is way more intuitive to set one up with a sine and one with a cosine, especially when they need to be phase shifted according to the signal that should be demodulated.

**Comment by jordens** [comment]
For demodulation you want to use the `cossin` stuff directly, or add complex output to the signal generator. Using two signal generators to do it is inefficient.

**Comment by jordens** [comment]
I still don't see when and why this would help. If you want names, then you can make a `const SINE_PHASE_OFFSET: f32 = -0.25;` and use that. Adding more code that does the same just with different names just means more code to test, check, maintain, document.

**Comment by svrotter** [comment]
The IQ thing was just the first thing that came to my mind. There are surely other situation I'd like to have that. At the end I'm replicating what I get offered by the AWGs I personally use and like.
If you don't want to have a naming that makes the device more user friendly outside of the rust code in interfaces like mine, where a `const SINE_PHASE_OFFSET` doesn't really help, it's fine. 
I'm not passionate about it, so just reject the request

**Comment by jordens** [comment]
As mentioned, a good design for IQ would give you IQ, not at twice the price I and Q separately. That doesn't appear to be a good argument. And having just looked at the first AWG that came to my mind, it's already a counterexample. It doesn't have two output options for sine and cosine but just one (plus the obvious phase shift). I'm always happy to make this more user friendly but I don't see where and how this achieves it.

**Pull request closed without merging**
